python evaluate.py \
--dataset samsum \
--few_shot True \
--few_shot_size 100 \
--few_shot_seed 42 \
--val_dataset few_shot_default_val \
--load_model True \
--load_model_path few_shot_100_seed_42 \
--inference_bs 4 \
